---
- hosts: web
  become: yes
  tasks:
    - name: 5.2.10 Ensure PermitRootLogin is disbled
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: '^PermitRootLogin\s*[^n]'
      notify:  
        - Restart sshd

    - name: Find /etc/sudoers.d/ files
      ansible.builtin.find:
      paths:
        - /etc/sudoers.d/
      register: sudoers
      when:
        - low_complexity | bool
        - low_disruption | bool
        - medium_severity | bool
        - no_reboot_needed | bool
        - restrict_strategy | bool
        - sudo_require_authentication | bool
     

 
