---
- hosts: web
  become: yes
  tasks:
    - name: 5.2.10 Ensure PermitRootLogin is disbled
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: '^PermitRootLogin\s*[^n]'
      notify:  
        - Restart sshd
    - name: 5.4.1 - Require minimum number of required classes of characters in passwords
      lineinfile:
        path: /etc/security/pwquality.conf
        line: minclass = 4
        regexp: "^minclass = 4"
        insertafter: "^# minclass = 0"
        
    - name: 5.5.1.1 - Ensure password expiration is {{ password_expire_days }} days or less
      lineinfile:
        dest: /etc/login.defs
        regexp: '^PASS_MAX_DAYS\s*((?!{{ password_expire_days }}).)*$'
        line: "PASS_MAX_DAYS  {{ password_expire_days }}"
      state: present
