---
- hosts: web
  become: yes
    tasks:
      - name: - Find all ssh public host keys
          find:
            paths: /etc/ssh
            file_type: file
            patterns: ssh_host_*_key.pub
            register: ssh_hostpub_out
            changed_when: false
