---
- hosts: web
  become: yes
  tasks:
    - name: 5.2.10 Ensure PermitRootLogin is disbled
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: '^PermitRootLogin\s*[^n]'
      notify:  
        - Restart sshd
    - name: 5.4.1 - Require minimum number of required classes of characters in passwords
      lineinfile:
        path: /etc/security/pwquality.conf
        line: minclass = 4
        regexp: "^minclass = 4"
        insertafter: "^# minclass = 0"
      when: password_req_digit
