---
- hosts: web
- name: "3.3.1 | PATCH | Ensure IP forwarding is disabled"
  when:
      - not rhel8cis_is_router
      - rhel8cis_rule_3_3_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - sysctl
      - patch
      - NIST800-53R5_CM-1
      - NIST800-53R5_CM-2
      - NIST800-53R5_CM-6
      - NIST800-53R5_CM-7
      - NIST800-53R5_IA-5
      - rule_3.3.1
  block:
      - name: "3.3.1 | PATCH | Ensure IP forwarding is disabled | Disable IPv4 forwarding"
        ansible.posix.sysctl:
            name: net.ipv4.ip_forward
            value: '0'
            ignoreerrors: true
            sysctl_file: "{{ rhel8cis_sysctl_file }}"
        notify: Sysctl_flush_ipv4_routes

      - name: "3.3.1 | PATCH | Ensure IP forwarding is disabled | Disable IPv6 forwarding"
        when:
            - rhel8cis_ipv6_required or
              rhel8cis_ipv6_sysctl_force
        ansible.posix.sysctl:
            name: net.ipv6.conf.all.forwarding
            value: '0'
            ignoreerrors: true
            sysctl_file: "{{ rhel8cis_sysctl_file }}"
        notify: Sysctl_flush_ipv6_routes
