---
- hosts: web
-  become: yes
  tasks:
    - name: 5.2.10 Ensure PermitRootLogin is disbled
      lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: '^PermitRootLogin\s*[^n]'
      notify:  
        - Restart sshd
